Issue 85 increase sidecar memory
Skatteetaten/terraform-nomad-minio pull request #91
Opened 2020-11-18 07:41 UTC by karimacherradi

## Closes/fixes/resolves issue(s)?
- closes #85 
## What was added/changed/fixed?

## Related issue(s)? [Optional]

## Others [Optional]

## Checklist (after created PR)
- [ ] Added reviewers
- [ ] Added assignee(s)
- [ ] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

2020-11-18 12:25 UTC, zhenik commented
Could you update: 
- README.md, input section, and example section
- in `example/minio_standalone/main.tf` setup `proxy_resource` variables explicit

2020-11-18 12:55 UTC, zhenik requested changes

2020-11-18 12:55 UTC, zhenik commented on example/minio_standalone/main.tf
> +  memory_proxy                    = 128
I think it should be
```suggestion
resource_proxy = {
  cpu = 200
  memory = 128
}
```

2020-11-18 12:55 UTC, zhenik commented on README.md
> +  memory_proxy                    = 128
```suggestion
resource_proxy = {
  cpu = 200
  memory = 128
}
```

2020-11-18 12:55 UTC, zhenik commented on README.md
> +| resource_proxy | Resource allocations for proxy | obj(number,number) | {cpu = 200,memory = 128} | no |
Linter :) 
```suggestion
| resource_proxy | Resource allocations for proxy | obj(number,number) | {cpu = 200,memory = 128} | no |
```

2020-11-18 13:00 UTC, claesgill commented on CHANGELOG.md
> +
```suggestion
```

2020-11-18 13:01 UTC, claesgill commented on README.md
> +| resource_proxy | Resource allocations for proxy | obj(number,number) | {cpu = 200,memory = 128} | no |
```suggestion
| resource_proxy | Resource allocations for proxy | obj(number,number) | { <br> cpu = 200, <br> memory = 128 <br> } | no |
```
`<br>` makes it more readable.

2020-11-18 13:01 UTC, claesgill commented on README.md
> +| resource_proxy | Resource allocations for proxy | obj(number,number) | {cpu = 200,memory = 128} | no |
```suggestion
| resource_proxy | Resource allocations for proxy | obj(number,number) | { <br> cpu = 200, <br> memory = 128 <br> } | no |
```
`<br>` makes it more readable.

2020-11-18 13:04 UTC, claesgill commented on main.tf
> +    memory_proxy              = var.resource_proxy.memory
Equal spacing, please 😄

2020-11-18 13:09 UTC, karimacherradi commented on main.tf
> +    memory_proxy              = var.resource_proxy.memory
Okey :P

2020-11-18 13:16 UTC, pdmthorsrud commented on example/minio_standalone/main.tf
> +}
Should be indented. Not suggesting here, not quite sure how many spaces the indent is :sweat_smile:
```suggestion
resource_proxy = {
  cpu = 200
  memory = 128
}
```

2020-11-18 13:42 UTC, pdmthorsrud approved these changes

2020-11-18 14:14 UTC, zhenik approved these changes
LGMT

2020-11-19 06:03 UTC, claesgill approved these changes
# 🚀

2020-11-19 06:14 UTC, dangernil approved these changes

2020-11-19 06:30 UTC, merged